main: jp.meao0525.battleemblem.BattleEmblemMain
name: BattleEmblem
version: ${project.version}
api-version: 1.14.4
#--
commands:
  be:
    description: BattleEmblem command.
    usage: /<command> [help] or [score] or [start]
    permission-message: You don't have <permission>
